# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# User Service Configuration (for Feign client)
user.service.url=http://user-service:8084

# JWT Configuration
jwt.secret=ujh0um82EHE7BVHGSL62MG0uKZqGbpXQWrdkvJCxN78=
jwt.expiration=86400000

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=8085

# Logging
logging.level.app.authentication.auth_service=DEBUG
logging.level.org.springframework.security=DEBUG