# Database Configuration
spring.datasource.url=jdbc:postgresql://file-storage-db:5432/file_storage_service
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# File Storage Configuration
file.upload-dir=/app/uploads/

# OpenTelemetry Configuration
otel.exporter.otlp.endpoint=http://otel-collector:4317
otel.resource.attributes[deployment.environment]=docker

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=8087

# Logging
logging.level.com.filestorage.filestorage=DEBUG
logging.level.org.springframework.security=DEBUG
