otel.service.name=${OTEL_SERVICE_NAME:user-service}
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
otel.resource.attributes=${OTEL_RESOURCE_ATTRIBUTES:service.name=user-service}
otel.logs.exporter=otlp
otel.instrumentation.logback.enabled=true