package com.merchant.merchant.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.dao.DataIntegrityViolationException;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import com.merchant.merchant.entity.Merchant;
import com.merchant.merchant.entity.MerchantDocument;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=validate",
        "spring.flyway.enabled=true"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Testcontainers(disabledWithoutDocker = true)
class MerchantRepositoryTest {

    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15-alpine");

    @Autowired
    private MerchantRepository merchantRepository;

    @Autowired
    private MerchantDocumentRepository documentRepository;

    private Merchant createMerchant(String name) {
        Merchant merchant = new Merchant();
        merchant.setUserId(1L);
        merchant.setName(name);
        return merchant;
    }

    private MerchantDocument createDocument(Long merchantId) {
        MerchantDocument doc = new MerchantDocument();
        doc.setMerchantId(merchantId);
        doc.setDocumentType("NIB");
        doc.setDocumentUrl("https://docs.example.com/nib.pdf");
        return doc;
    }

    // ---- MerchantRepository ----

    @Test
    void save_persistsMerchantWithGeneratedIdTimestampsAndAutoGeneratedNoApiKey() {
        Merchant saved = merchantRepository.save(createMerchant("Merchant1"));

        assertThat(saved.getMerchantId()).isNotNull();
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getUpdatedAt()).isNotNull();
        assertThat(saved.getDeletedAt()).isNull();
        assertThat(saved.getStatus()).isEqualTo("PENDING");
        // @PrePersist auto-generates UUID strings when null
        assertThat(saved.getMerchantNo()).isNotBlank();
        assertThat(saved.getApiKey()).isNotBlank();
    }

    @Test
    void save_autogeneratedMerchantNoAndApiKeyAreUniqueAcrossRows() {
        Merchant m1 = merchantRepository.save(createMerchant("Merchant1"));
        Merchant m2 = merchantRepository.save(createMerchant("Merchant2"));

        assertThat(m1.getMerchantNo()).isNotEqualTo(m2.getMerchantNo());
        assertThat(m1.getApiKey()).isNotEqualTo(m2.getApiKey());
    }

    @Test
    void save_rejectsDuplicateExplicitMerchantNo() {
        Merchant first = createMerchant("Merchant1");
        first.setMerchantNo("MCH-DUP-0001");
        merchantRepository.saveAndFlush(first);

        Merchant duplicate = createMerchant("Merchant2");
        duplicate.setMerchantNo("MCH-DUP-0001");

        assertThatThrownBy(() -> merchantRepository.saveAndFlush(duplicate))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void findById_returnsSavedMerchant() {
        Merchant saved = merchantRepository.save(createMerchant("Merchant2"));

        Optional<Merchant> found = merchantRepository.findById(saved.getMerchantId());

        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("Merchant2");
        assertThat(found.get().getUserId()).isEqualTo(1L);
    }

    @Test
    void findById_returnsEmptyWhenMissing() {
        assertThat(merchantRepository.findById(999999L)).isEmpty();
    }

    @Test
    void findByMerchantNo_returnsMatchingMerchant() {
        Merchant saved = merchantRepository.save(createMerchant("Merchant3"));

        Optional<Merchant> found = merchantRepository.findByMerchantNo(saved.getMerchantNo());

        assertThat(found).isPresent();
        assertThat(found.get().getMerchantId()).isEqualTo(saved.getMerchantId());
    }

    @Test
    void findByMerchantNo_returnsEmptyForUnknownNo() {
        assertThat(merchantRepository.findByMerchantNo("MCH-UNKNOWN")).isEmpty();
    }

    @Test
    void findByApiKey_returnsMatchingMerchant() {
        Merchant saved = merchantRepository.save(createMerchant("Merchant4"));

        Optional<Merchant> found = merchantRepository.findByApiKey(saved.getApiKey());

        assertThat(found).isPresent();
        assertThat(found.get().getMerchantId()).isEqualTo(saved.getMerchantId());
    }

    @Test
    void findByApiKey_returnsEmptyForUnknownKey() {
        assertThat(merchantRepository.findByApiKey("unknown-api-key")).isEmpty();
    }

    @Test
    void findByUserId_returnsOnlyThatUsersMerchants() {
        Merchant m1 = createMerchant("User1MerchantA");
        m1.setUserId(10L);
        Merchant m2 = createMerchant("User1MerchantB");
        m2.setUserId(10L);
        Merchant m3 = createMerchant("User2Merchant");
        m3.setUserId(20L);

        merchantRepository.save(m1);
        merchantRepository.save(m2);
        merchantRepository.save(m3);

        List<Merchant> result = merchantRepository.findByUserId(10L);

        assertThat(result).hasSize(2);
        assertThat(result).extracting(Merchant::getName)
                .containsExactlyInAnyOrder("User1MerchantA", "User1MerchantB");
    }

    @Test
    void findByUserId_returnsEmptyForUnknownUser() {
        assertThat(merchantRepository.findByUserId(999999L)).isEmpty();
    }

    @Test
    void update_touchesUpdatedAtViaPreUpdate() {
        Merchant saved = merchantRepository.save(createMerchant("Before"));
        LocalDateTime createdAtBefore = saved.getCreatedAt();

        saved.setName("After");
        saved.setDescription("Updated description");
        Merchant updated = merchantRepository.saveAndFlush(saved);

        assertThat(updated.getName()).isEqualTo("After");
        assertThat(updated.getDescription()).isEqualTo("Updated description");
        assertThat(updated.getCreatedAt()).isEqualTo(createdAtBefore);
        assertThat(updated.getUpdatedAt()).isNotNull();
        // merchantNo/apiKey untouched by update
        assertThat(updated.getMerchantNo()).isEqualTo(saved.getMerchantNo());
        assertThat(updated.getApiKey()).isEqualTo(saved.getApiKey());
    }

    @Test
    void delete_removesMerchantRow() {
        Merchant saved = merchantRepository.save(createMerchant("DeleteMe"));

        merchantRepository.delete(saved);
        merchantRepository.flush();

        assertThat(merchantRepository.findById(saved.getMerchantId())).isEmpty();
    }

    // ---- MerchantDocumentRepository ----

    @Test
    void save_persistsDocumentWithGeneratedIdAndTimestamps() {
        Merchant merchant = merchantRepository.save(createMerchant("MerchantWithDoc"));

        MerchantDocument saved = documentRepository.save(createDocument(merchant.getMerchantId()));

        assertThat(saved.getDocumentId()).isNotNull();
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getUpdatedAt()).isNotNull();
        assertThat(saved.getDeletedAt()).isNull();
        assertThat(saved.getStatus()).isEqualTo("PENDING");
    }

    @Test
    void findByMerchantId_returnsOnlyThatMerchantsDocuments() {
        Merchant merchant = merchantRepository.save(createMerchant("MerchantDocsA"));
        Merchant other = merchantRepository.save(createMerchant("MerchantDocsB"));

        documentRepository.save(createDocument(merchant.getMerchantId()));
        documentRepository.save(createDocument(merchant.getMerchantId()));
        documentRepository.save(createDocument(other.getMerchantId()));

        List<MerchantDocument> result = documentRepository.findByMerchantId(merchant.getMerchantId());

        assertThat(result).hasSize(2);
        assertThat(result).allMatch(d -> d.getMerchantId().equals(merchant.getMerchantId()));
    }

    @Test
    void findByMerchantId_returnsEmptyWhenNoDocuments() {
        assertThat(documentRepository.findByMerchantId(999999L)).isEmpty();
    }

    @Test
    void delete_removesDocumentRow() {
        Merchant merchant = merchantRepository.save(createMerchant("MerchantDocDelete"));
        MerchantDocument saved = documentRepository.save(createDocument(merchant.getMerchantId()));

        documentRepository.delete(saved);
        documentRepository.flush();

        assertThat(documentRepository.findById(saved.getDocumentId())).isEmpty();
    }
}
