spring.application.name=email-service
server.port=8094
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=email-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
otel.service.name=email-service
otel.exporter.otlp.endpoint=http://otel-collector:4317
management.endpoints.web.exposure.include=health,info,metrics,prometheus